### ISSUE TITLE
Using on mobile

### ISSUE THREAD

**Issue by vsouto** [jbergknoff/guitar-tuner#2]
Hey man, how are you?

Did you or anybody tried to use it on a mobile app?

Cause i just putted your code on an app of mine and doesnt seem to work.
In the browser it worked great, but not when i build with Ionic.

I'll try to debug now

**Comment by jbergknoff** [comment]
Hi, thanks for bringing this up. I haven't tried to run this code in a mobile environment. Good luck debugging.
